import { MallaZoneInfo, ZoneId, MallaMission } from '../types';

export const TEMPORAL_ISLAND_MAP_IMG = '/src/assets/images/temporal_island_v2_1791326701355.jpg';
export const KRONOS_CENTRAL_CLOCK_IMG = '/src/assets/images/kronos_central_clock_1791323248576.jpg';
export const TEMPORAL_STORM_FOG_IMG = '/src/assets/images/temporal_storm_fog_1791323257751.jpg';

/**
 * 12 Zonas de la Malla Temporal situadas en la Isla de Realidades Cuánticas.
 * Cada zona posee 3 misiones específicas y únicas para abrir los candados temporales y rescatar el reino.
 * Las coordenadas y territorios coinciden visualmente con la geografía de la isla:
 * - Volcán: Esquina superior derecha (con magma ardiente)
 * - Jurásico: Esquina inferior izquierda (valle de dinosaurios y fósiles, totalmente separado del volcán)
 * - Glaciar: Esquina superior izquierda (montañas nevadas)
 * - Sakura: Centro superior (jardines rosados y pagodas)
 * - Desierto: Centro-derecha (pirámides doradas)
 * - Ciudad Ciberpunk / Krono: Esquina inferior derecha (rascacielos neón)
 * - Steampunk: Centro inferior (fábrica de engranajes y vapor)
 * - Piratas: Costa este (playa tropical y galeones)
 * - Castillo Medieval: Centro-izquierda inferior (fortaleza de piedra)
 * - Jungla Maya: Centro-izquierda (ruinas y cascadas)
 * - Neón: Arboleda cibernética bioluminiscente
 * - Base Lunar: Estación orbital cósmica
 */
export const MALLA_ZONES: MallaZoneInfo[] = [
  // 1. BOSQUE NEÓN
  {
    id: 'neon',
    name: 'Reino Neón',
    subtitle: 'Arboleda Bioluminiscente Ancestral',
    themeColor: '#22d3ee',
    accentColor: '#4ade80',
    bossName: 'Guardián Neón MK-IV',
    mapCoords: { x: 30, y: 34 },
    territory: { left: 22, top: 24, width: 18, height: 20 },
    loreCorruption: 'La tormenta temporal ha sobrecargado los generadores del bosque neón, envolviendo sus árboles en un vórtice de radiación de plasma.',
    missions: [
      {
        id: 'neon_m1',
        zoneId: 'neon',
        missionIndex: 0,
        title: 'Revancha: Guardián Neón MK-IV',
        description: 'Vuelve a enfrentarte al mecha ancestral en el santuario neón y neutraliza su núcleo inestable.',
        objectiveText: 'Derrota al Guardián Neón MK-IV en el Acto 3',
        type: 'boss',
        levelId: 'neon-3',
        levelIndex: 2,
        rewardScore: 3500,
      },
      {
        id: 'neon_m2',
        zoneId: 'neon',
        missionIndex: 1,
        title: 'Sobrecarga de Red Cuántica',
        description: 'Cruza la arboleda de neon antes de que la corriente temporal colapse la red.',
        objectiveText: 'Completa el Acto 1 en menos de 140 segundos',
        type: 'time',
        levelId: 'neon-1',
        levelIndex: 0,
        timeLimitSec: 140,
        rewardScore: 2800,
      },
      {
        id: 'neon_m3',
        zoneId: 'neon',
        missionIndex: 2,
        title: 'Bioluminiscencia Pura',
        description: 'Recolecta las esferas de energía concentrada entre las raíces cibernéticas.',
        objectiveText: 'Consigue al menos 38 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'neon-2',
        levelIndex: 1,
        targetCrystals: 38,
        rewardScore: 3000,
      },
    ],
  },

  // 2. CEREZO ESPIRITUAL
  {
    id: 'sakura',
    name: 'Reino Sakura',
    subtitle: 'El Sendero Sagrado de los Pétalos',
    themeColor: '#f472b6',
    accentColor: '#fb7185',
    bossName: 'Maestra Kunoichi Rosa',
    mapCoords: { x: 44, y: 18 },
    territory: { left: 34, top: 8, width: 20, height: 20 },
    loreCorruption: 'El flujo del viento espiritual se detuvo: los pétalos quedan suspendidos en el aire bajo densos nubarrones de éter.',
    missions: [
      {
        id: 'sakura_m1',
        zoneId: 'sakura',
        missionIndex: 0,
        title: 'Duelo de las Cien Sombras: Kunoichi',
        description: 'Supera las ilusiones y dagas de viento de la protectora del dojo sagrado.',
        objectiveText: 'Derrota a la Maestra Kunoichi en el Acto 3',
        type: 'boss',
        levelId: 'sakura-3',
        levelIndex: 5,
        rewardScore: 3800,
      },
      {
        id: 'sakura_m2',
        zoneId: 'sakura',
        missionIndex: 1,
        title: 'Vuelo de Pétalos Fugaces',
        description: 'Salta entre los tejados pagodas a toda prisa esquivando las trampas de viento.',
        objectiveText: 'Completa el Acto 1 en menos de 150 segundos',
        type: 'time',
        levelId: 'sakura-1',
        levelIndex: 3,
        timeLimitSec: 150,
        rewardScore: 3000,
      },
      {
        id: 'sakura_m3',
        zoneId: 'sakura',
        missionIndex: 2,
        title: 'Faroles de los Ancestros',
        description: 'Encuentra y reúne las gemas espirituales ocultas en el bosque de cerezos.',
        objectiveText: 'Consigue al menos 42 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'sakura-2',
        levelIndex: 4,
        targetCrystals: 42,
        rewardScore: 3200,
      },
    ],
  },

  // 3. ACANTILADOS DE LAVA (VOLCÁN - ESQUINA SUPERIOR DERECHA)
  {
    id: 'lavacliff',
    name: 'Reino Volcánico',
    subtitle: 'Caldera de Magma y Núcleo Ígneo',
    themeColor: '#f97316',
    accentColor: '#ef4444',
    bossName: 'Dragón de Magma Ignis',
    mapCoords: { x: 74, y: 24 },
    territory: { left: 64, top: 10, width: 24, height: 24 },
    loreCorruption: 'La caldera volcánica del noreste ruge con cenizas oscuras; el magma arde en descontrol amenazando con calcinar la isla.',
    missions: [
      {
        id: 'lavacliff_m1',
        zoneId: 'lavacliff',
        missionIndex: 0,
        title: 'La Furia del Dragón Ignis',
        description: 'Enfrenta al titán de fuego sobre las plataformas de basalto en erupción.',
        objectiveText: 'Derrota al Dragón Ignis en el Acto 3',
        type: 'boss',
        levelId: 'lavacliff-3',
        levelIndex: 8,
        rewardScore: 4000,
      },
      {
        id: 'lavacliff_m2',
        zoneId: 'lavacliff',
        missionIndex: 1,
        title: 'Escape de la Ola de Lava',
        description: 'Esquiva los proyectiles ardientes y llega al portal de salida velozmente.',
        objectiveText: 'Completa el Acto 1 en menos de 140 segundos',
        type: 'time',
        levelId: 'lavacliff-1',
        levelIndex: 6,
        timeLimitSec: 140,
        rewardScore: 3200,
      },
      {
        id: 'lavacliff_m3',
        zoneId: 'lavacliff',
        missionIndex: 2,
        title: 'Piedras de Fuego Primordial',
        description: 'Extrae los cristales ígneos que brotan de las rocas ardientes.',
        objectiveText: 'Consigue al menos 35 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'lavacliff-2',
        levelIndex: 7,
        targetCrystals: 35,
        rewardScore: 3400,
      },
    ],
  },

  // 4. SANTUARIO DEL DESIERTO (CENTRO-DERECHA)
  {
    id: 'desert',
    name: 'Reino Desértico',
    subtitle: 'Pirámides Doradas y Reliquias de Arena',
    themeColor: '#f59e0b',
    accentColor: '#10b981',
    bossName: "Faraón Akhen'Ra",
    mapCoords: { x: 84, y: 46 },
    territory: { left: 74, top: 34, width: 22, height: 22 },
    loreCorruption: 'Una tormenta de arena oscura cubre las esfinges milenarias, atrapando las reliquias en un torbellino temporal.',
    missions: [
      {
        id: 'desert_m1',
        zoneId: 'desert',
        missionIndex: 0,
        title: "El Juicio del Faraón Akhen'Ra",
        description: 'Ingresa a la cámara funeraria y derrota al señor de las arenas doradas.',
        objectiveText: "Derrota a Akhen'Ra en el Acto 3",
        type: 'boss',
        levelId: 'desert-3',
        levelIndex: 11,
        rewardScore: 4200,
      },
      {
        id: 'desert_m2',
        zoneId: 'desert',
        missionIndex: 1,
        title: 'Carrera del Viento Khamsin',
        description: 'Cruza el mar de dunas antes de que el espejismo temporal devore el sendero.',
        objectiveText: 'Completa el Acto 1 en menos de 150 segundos',
        type: 'time',
        levelId: 'desert-1',
        levelIndex: 9,
        timeLimitSec: 150,
        rewardScore: 3300,
      },
      {
        id: 'desert_m3',
        zoneId: 'desert',
        missionIndex: 2,
        title: 'Tesoros de la Tumba de Oro',
        description: 'Recolecta las gemas solares sagradas de los escarabajos de Ra.',
        objectiveText: 'Consigue al menos 45 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'desert-2',
        levelIndex: 10,
        targetCrystals: 45,
        rewardScore: 3500,
      },
    ],
  },

  // 5. KRONO CITY (CIBERPUNK - ESQUINA INFERIOR DERECHA)
  {
    id: 'krono',
    name: 'Reino Ciberpunk',
    subtitle: 'Metrópolis Cuántica y Autopistas de Datos',
    themeColor: '#06b6d4',
    accentColor: '#8b5cf6',
    bossName: 'Titán Mecánico Kronos-Ω',
    mapCoords: { x: 74, y: 78 },
    territory: { left: 64, top: 68, width: 22, height: 22 },
    loreCorruption: 'Los rascacielos flotantes están asediados por relámpagos cibernéticos y drones fuera de control bajo niebla eléctrica.',
    missions: [
      {
        id: 'krono_m1',
        zoneId: 'krono',
        missionIndex: 0,
        title: 'Desconexión del Titán Kronos-Ω',
        description: 'Destruye el núcleo del gigante cibernético en la azotea del reactor central.',
        objectiveText: 'Derrota al Titán Kronos-Ω en el Acto 3',
        type: 'boss',
        levelId: 'krono-3',
        levelIndex: 14,
        rewardScore: 4500,
      },
      {
        id: 'krono_m2',
        zoneId: 'krono',
        missionIndex: 1,
        title: 'Autopista de Datos Extrema',
        description: 'Corre a máxima velocidad por los puentes magnéticos y compuertas láser.',
        objectiveText: 'Completa el Acto 1 en menos de 145 segundos',
        type: 'time',
        levelId: 'krono-1',
        levelIndex: 12,
        timeLimitSec: 145,
        rewardScore: 3500,
      },
      {
        id: 'krono_m3',
        zoneId: 'krono',
        missionIndex: 2,
        title: 'Minado de Microprocesadores',
        description: 'Recupera los paquetes de microdatos cuánticos flotando en la metrópolis.',
        objectiveText: 'Consigue al menos 50 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'krono-2',
        levelIndex: 13,
        targetCrystals: 50,
        rewardScore: 3700,
      },
    ],
  },

  // 6. JUNGLE RUN (CENTRO-IZQUIERDA)
  {
    id: 'jungle',
    name: 'Reino de la Jungla',
    subtitle: 'Pirámides Mayas y Árboles Gigantes',
    themeColor: '#10b981',
    accentColor: '#eab308',
    bossName: 'Balam, el Jaguar Ancestral',
    mapCoords: { x: 16, y: 46 },
    territory: { left: 6, top: 34, width: 22, height: 22 },
    loreCorruption: 'Una espesa niebla tropical de esporas venenosas ha enredado a las criaturas de la selva maya ancestral.',
    missions: [
      {
        id: 'jungle_m1',
        zoneId: 'jungle',
        missionIndex: 0,
        title: 'Duelo en el Cenote Sagrado: Balam',
        description: 'Vence a la bestia guardiana de jade en las ruinas del templo ceremonial.',
        objectiveText: 'Derrota al Jaguar Balam en el Acto 3',
        type: 'boss',
        levelId: 'jungle-3',
        levelIndex: 17,
        rewardScore: 4600,
      },
      {
        id: 'jungle_m2',
        zoneId: 'jungle',
        missionIndex: 1,
        title: 'Acrobacia en Lianas Mayas',
        description: 'Avanza por las copas de los árboles esquivando los dardos venenosos.',
        objectiveText: 'Completa el Acto 1 en menos de 155 segundos',
        type: 'time',
        levelId: 'jungle-1',
        levelIndex: 15,
        timeLimitSec: 155,
        rewardScore: 3600,
      },
      {
        id: 'jungle_m3',
        zoneId: 'jungle',
        missionIndex: 2,
        title: 'Jade Sagrado de Quetzalcóatl',
        description: 'Reúne las joyas verdes ocultas entre las raíces y cascadas de la selva.',
        objectiveText: 'Consigue al menos 40 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'jungle-2',
        levelIndex: 16,
        targetCrystals: 40,
        rewardScore: 3800,
      },
    ],
  },

  // 7. BLIZZARD RUSH (GLACIAR - ESQUINA SUPERIOR IZQUIERDA)
  {
    id: 'blizzard',
    name: 'Reino Glaciar',
    subtitle: 'Picos Nevados y Descenso en Esquí',
    themeColor: '#38bdf8',
    accentColor: '#93c5fd',
    bossName: 'Yukio el Yeti Colosal',
    mapCoords: { x: 18, y: 20 },
    territory: { left: 8, top: 8, width: 22, height: 22 },
    loreCorruption: 'Ventiscas congelantes y nubes de tormenta de hielo han sepultado los refugios alpinos bajo permafrost.',
    missions: [
      {
        id: 'blizzard_m1',
        zoneId: 'blizzard',
        missionIndex: 0,
        title: 'Batalla en la Ventisca: Yukio',
        description: 'Enfrenta al titán de las nieves en medio de una avalancha desatada.',
        objectiveText: 'Derrota a Yukio el Yeti en el Acto 3',
        type: 'boss',
        levelId: 'blizzard-3',
        levelIndex: 20,
        rewardScore: 4800,
      },
      {
        id: 'blizzard_m2',
        zoneId: 'blizzard',
        missionIndex: 1,
        title: 'Descenso Vertiginoso en Esquí',
        description: 'Esquiva las rocas congeladas a máxima velocidad pendiente abajo.',
        objectiveText: 'Completa el Acto 1 en menos de 140 segundos',
        type: 'time',
        levelId: 'blizzard-1',
        levelIndex: 18,
        timeLimitSec: 140,
        rewardScore: 3700,
      },
      {
        id: 'blizzard_m3',
        zoneId: 'blizzard',
        missionIndex: 2,
        title: 'Cristales Criogénicos del Pico',
        description: 'Recolecta las gemas criogénicas ocultas entre los pinos cubiertos de nieve.',
        objectiveText: 'Consigue al menos 38 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'blizzard-2',
        levelIndex: 19,
        targetCrystals: 38,
        rewardScore: 3900,
      },
    ],
  },

  // 8. STEAMPUNK (CENTRO INFERIOR)
  {
    id: 'steampunk',
    name: 'Reino Steampunk',
    subtitle: 'Fábrica de Engranajes y Vapor',
    themeColor: '#d97706',
    accentColor: '#fbbf24',
    bossName: 'Vulkan-Ω, Coloso del Reactor',
    mapCoords: { x: 50, y: 82 },
    territory: { left: 40, top: 72, width: 22, height: 20 },
    loreCorruption: 'Tuberías de vapor roto han cubierto los muelles mecánicos de un humo marrón impenetrable que asfixia los pistones.',
    missions: [
      {
        id: 'steampunk_m1',
        zoneId: 'steampunk',
        missionIndex: 0,
        title: 'Sobrecarga de Caldera: Vulkan-Ω',
        description: 'Desmantela la caldera andante de alta presión antes de que explote el reactor.',
        objectiveText: 'Derrota a Vulkan-Ω en el Acto 3',
        type: 'boss',
        levelId: 'steampunk-3',
        levelIndex: 23,
        rewardScore: 5000,
      },
      {
        id: 'steampunk_m2',
        zoneId: 'steampunk',
        missionIndex: 1,
        title: 'Maniobras entre Pistones',
        description: 'Sincroniza tus saltos sobre engranajes en rotación constante.',
        objectiveText: 'Completa el Acto 1 en menos de 150 segundos',
        type: 'time',
        levelId: 'steampunk-1',
        levelIndex: 21,
        timeLimitSec: 150,
        rewardScore: 3800,
      },
      {
        id: 'steampunk_m3',
        zoneId: 'steampunk',
        missionIndex: 2,
        title: 'Engranajes de Latón Cuántico',
        description: 'Recupera los núcleos de vapor perdidos en las tuberías de la fundición.',
        objectiveText: 'Consigue al menos 42 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'steampunk-2',
        levelIndex: 22,
        targetCrystals: 42,
        rewardScore: 4000,
      },
    ],
  },

  // 9. CASTLE SMASH (MEDIEVAL - INFERIOR CENTRO-IZQUIERDA)
  {
    id: 'castlesmash',
    name: 'Reino Medieval',
    subtitle: 'Fortaleza Feudal y Almenas de Piedra',
    themeColor: '#64748b',
    accentColor: '#f59e0b',
    bossName: 'Lord Malakar el Nigromante',
    mapCoords: { x: 34, y: 64 },
    territory: { left: 24, top: 54, width: 22, height: 22 },
    loreCorruption: 'Nubes de magia oscura y espectros cubren la fortaleza feudal; las catapultas disparan sin cesar.',
    missions: [
      {
        id: 'castlesmash_m1',
        zoneId: 'castlesmash',
        missionIndex: 0,
        title: 'Asedio a la Torre del Nigromante',
        description: 'Sube al pináculo del castillo y derrota al señor oscuro y su cortejo espectral.',
        objectiveText: 'Derrota a Lord Malakar en el Acto 3',
        type: 'boss',
        levelId: 'castlesmash-3',
        levelIndex: 26,
        rewardScore: 5200,
      },
      {
        id: 'castlesmash_m2',
        zoneId: 'castlesmash',
        missionIndex: 1,
        title: 'Asalto a las Murallas Feudales',
        description: 'Esquiva las rocas de catapulta y flechas llameantes para alcanzar el foso.',
        objectiveText: 'Completa el Acto 1 en menos de 145 segundos',
        type: 'time',
        levelId: 'castlesmash-1',
        levelIndex: 24,
        timeLimitSec: 145,
        rewardScore: 3900,
      },
      {
        id: 'castlesmash_m3',
        zoneId: 'castlesmash',
        missionIndex: 2,
        title: 'Reliquias de la Corona Real',
        description: 'Encuentra las joyas imperiales guardadas en las mazmorras de piedra.',
        objectiveText: 'Consigue al menos 40 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'castlesmash-2',
        levelIndex: 25,
        targetCrystals: 40,
        rewardScore: 4100,
      },
    ],
  },

  // 10. PIRATES TREASURE (COSTA ESTE)
  {
    id: 'piratestreasure',
    name: 'Reino Pirata',
    subtitle: 'Bahía Maldita y Naufragios Submarinos',
    themeColor: '#0284c7',
    accentColor: '#facc15',
    bossName: 'Capitán Barbanegra & El Cofre',
    mapCoords: { x: 88, y: 64 },
    territory: { left: 78, top: 54, width: 20, height: 22 },
    loreCorruption: 'Una niebla marina espectral y aguas agitadas esconden el archipiélago pirata; galeones fantasma patrullan la orilla.',
    missions: [
      {
        id: 'piratestreasure_m1',
        zoneId: 'piratestreasure',
        missionIndex: 0,
        title: 'Duelo en el Navío Fantasma',
        description: 'Vence al legendario pirata y libera el cofre del tesoro condenado.',
        objectiveText: 'Derrota al Capitán Barbanegra en el Acto 3',
        type: 'boss',
        levelId: 'piratestreasure-3',
        levelIndex: 29,
        rewardScore: 5400,
      },
      {
        id: 'piratestreasure_m2',
        zoneId: 'piratestreasure',
        missionIndex: 1,
        title: 'Fuga de la Bahía del Naufragio',
        description: 'Cruza los tablones y cocoteros esquivando los cañonazos de la fragata.',
        objectiveText: 'Completa el Acto 1 en menos de 150 segundos',
        type: 'time',
        levelId: 'piratestreasure-1',
        levelIndex: 27,
        timeLimitSec: 150,
        rewardScore: 4000,
      },
      {
        id: 'piratestreasure_m3',
        zoneId: 'piratestreasure',
        missionIndex: 2,
        title: 'El Botín del Océano Profundo',
        description: 'Bucea entre los restos del naufragio para recolectar las monedas de oro.',
        objectiveText: 'Consigue al menos 45 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'piratestreasure-2',
        levelIndex: 28,
        targetCrystals: 45,
        rewardScore: 4200,
      },
    ],
  },

  // 11. JURASSIC DRAFT (VALLE PREHISTÓRICO - ESQUINA INFERIOR IZQUIERDA - SEPARADO TOTALMENTE DEL VOLCÁN)
  {
    id: 'jurasicdraft',
    name: 'Reino Prehistórico',
    subtitle: 'Valle de los Dinosaurios y T-Rex Primordial',
    themeColor: '#15803d',
    accentColor: '#ea580c',
    bossName: 'T-Rex Titánico Primordial',
    mapCoords: { x: 16, y: 76 },
    territory: { left: 6, top: 66, width: 22, height: 24 },
    loreCorruption: 'Nubes de esporas mesozoicas ocultan el valle primitivo del suroeste; los rugidos del T-Rex sacuden el suelo ancestral.',
    missions: [
      {
        id: 'jurasicdraft_m1',
        zoneId: 'jurasicdraft',
        missionIndex: 0,
        title: 'El Rugido del T-Rex Primordial',
        description: 'Detén la embestida del mayor depredador de todos los tiempos en el nido de cráteres.',
        objectiveText: 'Derrota al T-Rex en el Acto 3',
        type: 'boss',
        levelId: 'jurasicdraft-3',
        levelIndex: 32,
        rewardScore: 5600,
      },
      {
        id: 'jurasicdraft_m2',
        zoneId: 'jurasicdraft',
        missionIndex: 1,
        title: 'Estampida de Raptores en el Valle',
        description: 'Corre a través del fango prehistórico y helechos gigantes sin detenerte.',
        objectiveText: 'Completa el Acto 1 en menos de 150 segundos',
        type: 'time',
        levelId: 'jurasicdraft-1',
        levelIndex: 30,
        timeLimitSec: 150,
        rewardScore: 4100,
      },
      {
        id: 'jurasicdraft_m3',
        zoneId: 'jurasicdraft',
        missionIndex: 2,
        title: 'Ámbar con ADN Prehistórico',
        description: 'Reúne las joyas de ámbar fósil escondidas en las cavernas del valle.',
        objectiveText: 'Consigue al menos 40 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'jurasicdraft-2',
        levelIndex: 31,
        targetCrystals: 40,
        rewardScore: 4300,
      },
    ],
  },

  // 12. THE MOON (ESTACIÓN ORBITAL LUNAR)
  {
    id: 'themoon',
    name: 'Reino Lunar',
    subtitle: 'Base Espacial y Plataforma Cósmica',
    themeColor: '#0f172a',
    accentColor: '#38bdf8',
    bossName: 'Centinela Supremo Doomsday',
    mapCoords: { x: 60, y: 14 },
    territory: { left: 50, top: 4, width: 20, height: 20 },
    loreCorruption: 'El vacío orbital se ha fracturado; una tormenta de antimateria envuelve los cohetes espaciales y andamios lunares.',
    missions: [
      {
        id: 'themoon_m1',
        zoneId: 'themoon',
        missionIndex: 0,
        title: 'Protocolo Centinela Doomsday',
        description: 'Desactiva el cañón cuántico y derrota al jefe de la frontera espacial.',
        objectiveText: 'Derrota al Centinela Doomsday en el Acto 3',
        type: 'boss',
        levelId: 'themoon-3',
        levelIndex: 35,
        rewardScore: 6000,
      },
      {
        id: 'themoon_m2',
        zoneId: 'themoon',
        missionIndex: 1,
        title: 'Lanzamiento Gravitatorio Lunar',
        description: 'Asciende por las plataformas de despegue en baja gravedad antes del bloqueo.',
        objectiveText: 'Completa el Acto 1 en menos de 160 segundos',
        type: 'time',
        levelId: 'themoon-1',
        levelIndex: 33,
        timeLimitSec: 160,
        rewardScore: 4300,
      },
      {
        id: 'themoon_m3',
        zoneId: 'themoon',
        missionIndex: 2,
        title: 'Núcleos de Helio-3 Estelar',
        description: 'Recolecta los cristales de energía estelar dispersos en la estación lunar.',
        objectiveText: 'Consigue al menos 50 cristales en el Acto 2',
        type: 'crystals',
        levelId: 'themoon-2',
        levelIndex: 34,
        targetCrystals: 50,
        rewardScore: 4500,
      },
    ],
  },
];

export function getMallaZones(): MallaZoneInfo[] {
  return MALLA_ZONES;
}

export function getMallaZone(zoneId: ZoneId): MallaZoneInfo | undefined {
  return MALLA_ZONES.find((z) => z.id === zoneId);
}

export function getMallaMission(zoneId: ZoneId, missionIndex: number): MallaMission | undefined {
  const zone = getMallaZone(zoneId);
  if (!zone) return undefined;
  return zone.missions[missionIndex];
}
